Repository flycheck/flycheck, pull requests merged in 2018-02, with the labels that each got.

#1385 Add cargo clippy
  CHANGES.rst
  doc/languages.rst
  flycheck.el
  test/specs/test-documentation.el
Labels: language support, needs review

#1113 Use python -c to invoke pylint and flake8
  CHANGES.rst
  flycheck.el
  maint/flycheck-checkdoc.el
Labels: language support, needs reply

#1388 Testing Emacs pretest on Travis
  .travis.yml
  Cask
  Makefile
  flycheck.el
  test/flycheck-test.el
  test/resources/language/emacs-lisp/check-declare-warnings.el
  test/resources/language/emacs-lisp/compressed.el.gz
  test/resources/language/emacs-lisp/warnings.el
  test/resources/language/emacs-lisp/warnings.el.gz
  test/specs/languages/test-javascript.el
Labels: tooling
