Repository flycheck/flycheck, pull requests merged in 2020-05, with the labels that each got.

#1752 Unify and improve help-echo text and error buffer messages
  flycheck.el
  test/flycheck-test.el
Labels: status: ready for review

#1742 Add two new indication modes: left-margin and right-margin
  CHANGES.rst
  doc/user/error-reports.rst
  flycheck.el
  test/flycheck-test.el
Labels: component: core, status: ready for review

#1743 Add customizable highlighting styles
  CHANGES.rst
  doc/user/error-reports.rst
  flycheck.el
Labels: component: core, status: ready for review

#1756 Tweak the modeline lighter and document it
  flycheck.el
  test/specs/test-mode-line.el
Labels: component: documentation, status: ready for review

#1763 Improve the usability and documentation of set-indication-mode
  doc/user/error-reports.rst
  flycheck.el
Labels: component: core

#1751 Plenty of small error list cleanups
  flycheck.el
  test/flycheck-test.el
  test/specs/test-error-list.el
Labels: component: error list

#1750 Cache results of flycheck-goto-line to speed up overlay creation
  CHANGES.rst
  flycheck.el
Labels: component: core, component: optimization

#1766 Add link to psalm.el and replace PHPStan's new web site
  doc/community/extensions.rst
Labels: component: checkers

#1749 Don't sort errors after receiving them from checkers
  CHANGES.rst
  flycheck-ert.el
  flycheck.el
Labels: component: core

#1755 Improve the UI for disabled checkers
  CHANGES.rst
  flycheck.el
  test/flycheck-test.el
Labels: component: core, status: ready for review

#1753 Allow custom error explainers
  CHANGES.rst
  doc/developer/developing.rst
  flycheck.el
Labels: component: checkers

#1772 Ensure that Python commands are run in the right buffer (closes GH-1770)
  flycheck.el
Labels: component: core

#1773 Ensure that flycheck-python-run-snippet is called in the right buffer
  flycheck.el
Labels: component: core
