Repository flycheck/flycheck, pull requests merged in 2020-03, with the labels that each got.

#1658 Add ruby-standardrb checker
  doc/languages.rst
  flycheck.el
  test/flycheck-test.el
  test/specs/languages/test-help.el
Labels: status: needs reply

#1213 pug checker: handle more error formats
  flycheck.el
  test/flycheck-test.el
  test/resources/language/pug/foo-base.pug
  test/resources/language/pug/foo-unknown-filter.pug
  test/resources/language/pug/foo.pug
Labels: component: checkers, status: needs reply

#1694 Fix tracking of temporary files in ELisp checker
  flycheck.el
Labels: status: ready for review

#1710 Autoload flycheck-define-checker to prevent unwanted argument expansion
  flycheck.el
Labels: status: ready for review

#1684 Further work on error ranges
  CHANGES.rst
  flycheck.el
  maint/flycheck-format.el
  test/flycheck-test.el
  test/resources/language/jsonnet/static_error.jsonnet
  test/specs/languages/test-javascript.el
  test/specs/languages/test-typescript.el
Labels: status: ready for review

#1696 Fall back to columns highlighting when error begins on a non-symbol
  flycheck.el
Labels: component: core, status: ready for review

#1476 [WIP] Fix unstable order of displayed errors
  flycheck.el
Labels: component: core, status: ready for review

#1662 Add next-checker only when not added
  flycheck.el
  test/flycheck-test.el
Labels: kind: bug, status: ready for review

#1700 Update issue template to mention Emacs.sx post and remove broken URLs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/user-support.md
  doc/contributor/contributing.rst
  doc/user/installation.rst
Labels: status: ready for review

#1701 Simplify and speed up flycheck-same-files-p by memoizing file-truename
  flycheck.el
Labels: status: ready for review

#1709 Add a nonempty buffer predicate to stylelint checkers
  flycheck.el
Labels: component: checkers, status: ready for review

#1707 Improve flycheck-compile
  CHANGES.rst
  flycheck.el
Labels: status: ready for review

#1712 Clean up config-file and option var declarations
  flycheck.el
Labels: component: checkers, status: ready for review

#1706 Properly handle empty strings from completing-read in -read-error-level
  flycheck.el
Labels: status: ready for review

#1695 Fix #1507 (allow Emacs Lisp checker to run without a buffer-file-name)
  CHANGES.rst
  flycheck.el
Labels: component: checkers, status: ready for review

#1714 Allow config-file variables to list multiple file names
  CHANGES.rst
  doc/languages.rst
  flycheck.el
  test/flycheck-test.el
Labels: status: ready for review

#1721 Add an :enabled test to haskell-stack-ghc
  flycheck.el
Labels: component: checkers
