Repository flycheck/flycheck, pull requests merged in 2020-04, with the labels that each got.

#1720 Move pylint to JSON and fix GH-1383
  flycheck.el
  test/flycheck-test.el
  test/resources/language/python/gh_1383.py
Labels: component: checkers

#1725 Speed up integration tests by removing an unconditional (sleep-for 1)
  flycheck-ert.el
Labels: status: ready for review

#1727 Fix error list highlighting
  flycheck.el
Labels: status: ready for review

#1724 Allow checkers to close stdin before reading all input
  flycheck-ert.el
  flycheck.el
  test/flycheck-test.el
Labels: status: ready for review

#1651 Use location of flake8 configuration file as working directory
  flycheck.el
Labels: kind: upstream

#1740 Fix links to next checkers in flycheck-describe-checker
  flycheck.el
Labels: component: core, status: ready for review
